services:
  frontend:
    image: ghcr.io/jonnas311/pdf-actions-frontend:${IMAGE_TAG:-latest}
    build: !reset null
    restart: unless-stopped

  backend:
    image: ghcr.io/jonnas311/pdf-actions-backend:${IMAGE_TAG:-latest}
    build: !reset null
    restart: unless-stopped

  minio:
    restart: unless-stopped